baseURL = 'https://lab.embedinker.com/'
locale = 'en-us'
title = 'Embedinker Labs'
theme = 'PaperMod'
mainSections = ["posts"]

[privacy]
  [privacy.vimeo]
    disabled = false
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[[menu.main]]
    name = "Labs"
    url = "/"
    weight = 5

[[menu.main]]
    name = "Coding"
    url = "/coding/"
    weight = 10

[[menu.main]]
    name = "Books & CppCon"
    url = "/reviews/"
    weight = 15

[[menu.main]]
    name = "Mia's Corner"
    url = "/cat/"
    weight = 30

[[menu.main]]
    name = "Systems & Organizing"
    url = "/organizing/"
    weight = 20
